using System;
using System.Collections.Generic;
using System.Text;
using ThaiDust.Core.Model.Persistent;

namespace ThaiDust.Core.Model
{
    public static class Stations
    {
        public static IList<Station> All = new List<Station>
        {
            new Station {Code = "02t", Name = "แขวงหิรัญรูจี เขตธนบุรี กรุงเทพ"},
            new Station {Code = "03t", Name = "ริมถนนกาญจนาภิเษก เขตบางขุนเทียน กรุงเทพ"},
            new Station {Code = "05t", Name = "แขวงบางนา เขตบางนา กรุงเทพ"},
            new Station {Code = "08t", Name = "ต.ทรงคนอง อ.พระประแดง จ.สมุทรปราการ"},
            new Station {Code = "10t", Name = "แขวงคลองจั่น เขตบางกะปิ กรุงเทพ"},
            new Station {Code = "11t", Name = "แขวงดินแดง เขตดินแดง กรุงเทพ"},
            new Station {Code = "12t", Name = "แขวงช่องนนทรี เขตยานนาวา กรุงเทพ"},
            new Station {Code = "13t", Name = "ต.บางกรวย อ.บางกรวย จ.นนทบุรี"},
            new Station {Code = "14t", Name = "ต.อ้อมน้อย อ.กระทุ่มแบน จ.สมุทรสาคร"},
            new Station {Code = "16t", Name = "ต.บางโปรง อ.เมือง จ.สมุทรปราการ"},
            new Station {Code = "17t", Name = "ต.ตลาด อ.พระประแดง จ.สมุทรปราการ"},
            new Station {Code = "18t", Name = "ต.ปากน้ำ อ.เมือง จ.สมุทรปราการ"},
            new Station {Code = "19t", Name = "ต.บางเสาธง อ.บางเสาธง จ.สมุทรปราการ"},
            new Station {Code = "20t", Name = "ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี"},
            new Station {Code = "21t", Name = "ต.ประตูชัย อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา"},
            new Station {Code = "22t", Name = "ต.บางพูด อ.ปากเกร็ด จ.นนทบุรี"},
            new Station {Code = "24t", Name = "ต.หน้าพระลาน อ.เฉลิมพระเกียรติ จ.สระบุรี"},
            new Station {Code = "25t", Name = "ต.ปากเพรียว อ.เมือง จ.สระบุรี"},
            new Station {Code = "26t", Name = "ต.หน้าเมือง อ.เมือง จ.ราชบุรี"},
            new Station {Code = "27t", Name = "ต.มหาชัย อ.เมือง จ.สมุทรสาคร"},
            new Station {Code = "28t", Name = "ต.ปลวกแดง, อ.ปลวกแดง, จ.ระยอง"},
            new Station {Code = "29t", Name = "ต.มาบตาพุด, อ.เมือง, จ.ระยอง"},
            new Station {Code = "30t", Name = "ต.ท่าประดู่, อ.เมือง, จ.ระยอง"},
            new Station {Code = "31t", Name = "ต.ห้วยโป่ง อ.เมือง จ.ระยอง"},
            new Station {Code = "32t", Name = "ต.ทุ่งสุขลา อ.ศรีราชา จ.ชลบุรี"},
            new Station {Code = "33t", Name = "ต.บ่อวิน อ.ศรีราชา จ.ชลบุรี"},
            new Station {Code = "34t", Name = "ต.บ้านสวน อ.เมือง จ.ชลบุรี"},
            new Station {Code = "35t", Name = "ต.ช้างเผือก อ.เมือง จ.เชียงใหม่"},
            new Station {Code = "36t", Name = "ต.ศรีภูมิ อ.เมือง จ.เชียงใหม่"},
            new Station {Code = "37t", Name = "ต.พระบาท อ.เมือง จ.ลำปาง"},
            new Station {Code = "38t", Name = "ต.สบป้าด อ.แม่เมาะ จ.ลำปาง"},
            new Station {Code = "39t", Name = "ต.บ้านดง อ.แม่เมาะ จ.ลำปาง"},
            new Station {Code = "40t", Name = "ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง"},
            new Station {Code = "41t", Name = "ต.ปากน้ำโพ อ.เมือง จ.นครสวรรค์"},
            new Station {Code = "42t", Name = "ต.มะขามเตี้ย อ.เมือง จ.สุราษฎร์ธานี"},
            new Station {Code = "43t", Name = "ต.ตลาดใหญ่ อ.เมือง จ.ภูเก็ต"},
            new Station {Code = "44t", Name = "ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา"},
            new Station {Code = "46t", Name = "ต.ในเมือง อ.เมือง จ.ขอนแก่น"},
            new Station {Code = "47t", Name = "ต.ในเมือง อ.เมือง จ.นครราชสีมา"},
            new Station {Code = "50t", Name = "ริมถนนพระรามสี่, เขตปทุมวัน, กรุงเทพ"},
            new Station {Code = "52t", Name = "ริมถนนอินทรพิทักษ์ เขตธนบุรี กรุงเทพ"},
            new Station {Code = "53t", Name = "ริมถนนลาดพร้าว เขตวังทองหลาง กรุงเทพ"},
            new Station {Code = "54t", Name = "ริมถนนดินแดง เขตดินแดง กรุงเทพ"},
            new Station {Code = "57t", Name = "ต.เวียง อ.เมือง จ.เชียงราย"},
            new Station {Code = "58t", Name = "ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน"},
            new Station {Code = "59t", Name = "แขวงพญาไท เขตพญาไท กรุงเทพ"},
            new Station {Code = "60t", Name = "ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา"},
            new Station {Code = "61t", Name = "แขวงพลับพลา เขตวังทองหลาง กรุงเทพ"},
            new Station {Code = "62t", Name = "ต.บางนาค อ.เมือง จ.นราธิวาส"},
            new Station {Code = "63t", Name = "ต.สะเตง อ.เมือง จ.ยะลา"},
            new Station {Code = "67t", Name = "ต.ในเวียง อ.เมือง จ.น่าน"},
            new Station {Code = "68t", Name = "ต.บ้านกลาง อ.เมือง จ.ลำพูน"},
            new Station {Code = "69t", Name = "ต.นาจักร อ.เมือง จ.แพร่"},
            new Station {Code = "70t", Name = "ต.บ้านต๋อม อ.เมืองพะเยา จ.พะเยา"},
            new Station {Code = "71t", Name = "ต.อรัญประเทศ อ.อรัญประเทศ จ.สระแก้ว"},
            new Station {Code = "72t", Name = "ต.นาอาน อ.เมือง จ.เลย"},
            new Station {Code = "73t", Name = "ต.เวียงพางคำ, อ.แม่สาย, จ.เชียงราย"},
            new Station {Code = "74t", Name = "ต.เนินพระ อ.เมือง จ.ระยอง"},
            new Station {Code = "75t", Name = "ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน"},
            new Station {Code = "76t", Name = "ต.แม่ปะ อ.แม่สอด จ.ตาก"},
            new Station {Code = "77t", Name = "ต.ท่าตูม อ.ศรีมหาโพธิ จ.ปราจีนบุรี"},
            new Station {Code = "78t", Name = "ต.เบตง อ.เบตง จ.ยะลา"},
            new Station {Code = "79t", Name = "ต.บ้านเหนือ อ.เมือง จ.กาญจนบุรี"},
            new Station {Code = "80t", Name = "ต.พิมาน อ.เมือง จ.สตูล"},
            new Station {Code = "81t", Name = "ต.นครปฐม อ.เมือง จ.นครปฐม"},
            new Station {Code = "m8", Name = "หน่วยตรวจวัดเคลื่อนที่ 8 ค่ายมหาสุรสิงหนาท จ.ระยอง"}
        };
    }
}
